#cloud-config tevbox

locale: en_US.UTF-8
timezone: UTC
users:
  - name: technat
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL # Allow any operations using sudo
    gecos: "It's me! Technat"
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJov21J2pGxwKIhTNPHjEkDy90U8VJBMiAodc2svmnFC cardno:000618187880

apt:
  sources:
    tailscale:
      source: "deb [signed-by=$KEY_FILE] https://pkgs.tailscale.com/stable/ubuntu jammy main"
      keyid: 458CA832957F5868
package_update: true
package_upgrade: true
packages:
  - vim
  - git
  - wget
  - curl
  - dnsutils
  - tailscale

write_files:
  - path: /etc/sysctl.d/99-tailscale.conf
    content: |
      net.ipv4.ip_forward          = 1
      net.ipv6.conf.all.forwarding = 1
runcmd:
  - systemctl disable ssh # we use tailscale ssh or console
  - sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
  - sudo tailscale up --ssh --auth-key "${tailnet_auth_key}"
