#cloud-config tevbox

locale: en_US.UTF-8
timezone: UTC
users:
  - name: ${username}
    groups: sudo
    sudo: "ALL=(ALL) NOPASSWD:ALL" # Allow any operations using sudo
    gecos: "It's me! ${username}"
    %{ if password == "" }
    lock_passwd: true
    %{ else }
    lock_passwd: false
    plain_text_passwd: ${password}
    %{ endif }
    shell: /bin/bash
    ssh_authorized_keys:
    %{ for ssh_key in ssh_keys ~}
     - ${ssh_key}
    %{ endfor ~}

apt:
  sources:
    tailscale:
      source: "deb [signed-by=$KEY_FILE] https://pkgs.tailscale.com/stable/ubuntu jammy main"
      keyid: 458CA832957F5868
package_update: true
package_upgrade: true
packages:
  - jq
  - vim
  - git
  - wget
  - curl
  - ufw
  - dnsutils
  - tailscale
  - hcloud-cli

write_files:
  - path: /etc/sysctl.d/99-tailscale.conf
    content: |
      net.ipv4.ip_forward          = 1
      net.ipv6.conf.all.forwarding = 1
  - path: /etc/ssh/sshd_config
    content: |
      Port ${ssh_port}
      PermitRootLogin no
      PermitEmptyPasswords no
      PasswordAuthentication yes
      PubkeyAuthentication yes
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      UsePAM yes
      X11Forwarding no
      PrintMotd no
      AcceptEnv LANG LC_*
      Subsystem    sftp    /usr/lib/openssh/sftp-server
      Include /etc/ssh/sshd_config.d/*.conf
  - path: /usr/local/bin/destroy-machine
    permissions: "0755"
    content: |
      #!/bin/sh
      # first grab the ID of our DNS record and delete this one
      recordID=$(curl -sSL "https://dns.hetzner.com/api/v1/records?zone_id=${zone_id}" -H 'Auth-API-Token: ${hetzner_dns_token}'  | jq '.records[] | select(.name=="${hostname}") | .id' | tr -d "\"")
      curl -X "DELETE" "https://dns.hetzner.com/api/v1/records/$recordID" -H 'Auth-API-Token: ${hetzner_dns_token}'
      
      # then dispatch the deletion of the server 2s after we have logged out of our tailnet
      (HCLOUD_TOKEN=${hcloud_token} hcloud server delete ${hostname}) & 
      (sudo tailscale funnel 443 off && sudo tailscale serve reset && sudo tailscale logout) &
runcmd:
  - systemctl restart sshd
  - sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
  - sudo tailscale up --ssh --auth-key "${tailnet_auth_key}"
  - sudo ufw allow in on tailscale0
  - sudo ufw default deny incoming
  - sudo ufw default allow outgoing
  - sudo ufw allow ${ssh_port}
  - sudo ufw enable