#cloud-config tevbox

locale: en_US.UTF-8
timezone: UTC
users:
  - name: technat
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL # Allow any operations using sudo
    gecos: "It's me! Technat"
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJov21J2pGxwKIhTNPHjEkDy90U8VJBMiAodc2svmnFC cardno:000618187880

apt:
  sources:
    tailscale:
      source: "deb [signed-by=$KEY_FILE] https://pkgs.tailscale.com/stable/ubuntu jammy main"
      keyid: 458CA832957F5868
package_update: true
package_upgrade: true
packages:
  - vim
  - git
  - wget
  - curl
  - ufw
  - dnsutils
  - tailscale

write_files:
  - path: /etc/sysctl.d/99-tailscale.conf
    content: |
      net.ipv4.ip_forward          = 1
      net.ipv6.conf.all.forwarding = 1
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      PermitRootLogin no
      PermitEmptyPasswords no
      PasswordAuthentication no
      PubkeyAuthentication yes
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      UsePAM yes
      X11Forwarding no
      PrintMotd no
      AcceptEnv LANG LC_*
      Subsystem    sftp    /usr/lib/openssh/sftp-server
      Include /etc/ssh/sshd_config.d/*.conf
  - path: /etc/systemd/system/termination-handler.service
    content: |
      [Unit]
      Description=Handle instance termination
      Wants=network-online.target
      After=cloud-final.service

      [Service]
      User=root
      WorkingDirectory=/opt/termination-handler/
      ExecStart=go run main.go
      Environment=TELEGRAM_API_KEY="${telegram_api_key}"
      Restart=never

      [Install]
      WantedBy=cloud-init.target
runcmd:
  - systemctl daemon-reload
  - systemctl restart sshd
  - systemctl enable --now termination-handler.service
  - sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
  - sudo tailscale up --ssh --auth-key "${tailnet_auth_key}"
  - sudo ufw allow in on tailscale0
  - sudo ufw default deny incoming
  - sudo ufw default allow outgoing
  - sudo ufw allow ssh
  - sudo ufw enable
