#cloud-config tevbox

locale: en_US.UTF-8
timezone: UTC

write_files:
  - path: /usr/local/bin/destroy-machine
    permissions: "0755"
    content: |
      #!/bin/sh
      # first grab the ID of our DNS record and delete this one
      recordID=$(curl -sSL "https://dns.hetzner.com/api/v1/records?zone_id=${zone_id}" -H 'Auth-API-Token: ${hetzner_dns_token}'  | jq '.records[] | select(.name=="${hostname}") | .id' | tr -d "\"")
      curl -X "DELETE" "https://dns.hetzner.com/api/v1/records/$recordID" -H 'Auth-API-Token: ${hetzner_dns_token}'

      # then dispatch the deletion of the server 2s after we have logged out of our tailnet
      (HCLOUD_TOKEN=${hcloud_token} hcloud server delete ${hostname}) & 
      (sudo tailscale funnel 443 off && sudo tailscale serve reset && sudo tailscale logout) &
