#cloud-config tevbox

locale: en_US.UTF-8
timezone: UTC
users:
  - name: technat
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL # Allow any operations using sudo
    gecos: "It's me! Technat"
    lock_passwd: false
    plain_text_passwd: ${user_password}
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJov21J2pGxwKIhTNPHjEkDy90U8VJBMiAodc2svmnFC cardno:000618187880

apt:
  sources:
    tailscale:
      source: "deb [signed-by=$KEY_FILE] https://pkgs.tailscale.com/stable/ubuntu jammy main"
      keyid: 458CA832957F5868
package_update: true
package_upgrade: true
packages:
  - vim
  - git
  - wget
  - curl
  - ufw
  - dnsutils
  - tailscale
  - python3-openstackclient

write_files:
  - path: /etc/sysctl.d/99-tailscale.conf
    content: |
      net.ipv4.ip_forward          = 1
      net.ipv6.conf.all.forwarding = 1
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      PermitRootLogin no
      PermitEmptyPasswords no
      PasswordAuthentication yes
      PubkeyAuthentication yes
      ChallengeResponseAuthentication no
      KbdInteractiveAuthentication no
      UsePAM yes
      X11Forwarding no
      PrintMotd no
      AcceptEnv LANG LC_*
      Subsystem    sftp    /usr/lib/openssh/sftp-server
      Include /etc/ssh/sshd_config.d/*.conf
  - path: /etc/environment
    content: |
      OS_AUTH_TYPE="v3applicationcredential"
      OS_AUTH_URL="https://api.pub1.infomaniak.cloud/identity"
      OS_IDENTITY_API_VERSION=3
      OS_REGION_NAME="dc3-a"
      OS_INTERFACE="public"
      OS_APPLICATION_CREDENTIAL_ID="${os_secret_id}"
      OS_APPLICATION_CREDENTIAL_SECRET="${os_secret_key}"
  - path: /usr/local/bin/destroy-machine.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      export OS_AUTH_TYPE=v3applicationcredential
      export OS_AUTH_URL=https://api.pub1.infomaniak.cloud/identity
      export OS_IDENTITY_API_VERSION=3
      export OS_REGION_NAME="dc3-a"
      export OS_INTERFACE=public
      export OS_APPLICATION_CREDENTIAL_ID=${os_secret_id}
      export OS_APPLICATION_CREDENTIAL_SECRET=${os_secret_key}
      sudo tailscale logout
      sleep 5s
      openstack server delete ${hostname} && openstack application credential delete ${hostname}
runcmd:
  - systemctl restart sshd
  - sudo sysctl -p /etc/sysctl.d/99-tailscale.conf
  - sudo tailscale up --ssh --auth-key "${tailnet_auth_key}"
  - sudo ufw allow in on tailscale0
  - sudo ufw default deny incoming
  - sudo ufw default allow outgoing
  - sudo ufw allow ssh
  - sudo ufw enable
