---
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validatio
argument_specs:
  # roles/openstack/tasks/main.yml entry point
  main:
    short_description: The main entry point for the openstack role.
    options:
      openstack_auth_url:
        type: "str"
        required: true
        description: "The string value"
      openstack_username:
        type: "str"
        required: true
        description: "The string value"
      openstack_password:
        type: "str"
        required: true
        description: "The string value"
      openstack_project_name:
        type: "str"
        required: true
        description: "The string value"
