name: Checks

on:
 pull_request:
 push: 

env:
  STATE_BUCKET: "tevbox-state"
  STATE_BUCKET_REGION: "eu-west-1" 

jobs:
  terraform:
    name: "Terraform Checks"
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::141091412313:role/tevbox-role
          role-session-name: tevbox
          aws-region: ${{ env.STATE_BUCKET_REGION }}
      - name: Create Terraform backend configuration
        run: |
          tee s3.tfbackend << END
            bucket = "${{ env.STATE_BUCKET }}"
            key    = "ci"
            region = "${{ env.STATE_BUCKET_REGION }}"
          END
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=s3.tfbackend
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
  ansible:
    name: "Ansible Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24