name: Create new instance

on:
  workflow_dispatch:
    inputs:
      hostname:
        type: string
        default: ""
        description: Hostname of the instance (if empty will be generated)
      username: 
        type: string
        default: technat
        description: Admin user to create
      password:
        type: string
        default: ""
        description: Password for user created by cloud-init (empty means it's disabled)
      ssh_key: 
          type: string
          default: ""
          description: SSH key to configure for the admin user
      ssh_port: 
        type: string
        default: '22'
        description: SSH port to configure
      type:
        type: choice
        default: cx11
        options: 
          - cx11
          - cpx11
          - cx22
          - cpx22
          - cx31
          - cpx31
          - cax11
          - cax21
          - cax31
        description: Size of the instance to create (cax=arm64)
      flavor:
        type: choice
        default: ubuntu-22.04
        options:
          - ubuntu-20.04
          - ubuntu-22.04
          - debian-10
          - debian-11
          - centos-7
          - centos-stream-8
          - centos-stream-9
          - rocky-8
          - rocky-9
          - fedora-37
        description: OS Flavor
      location:
        type: choice
        default: hel1
        options:
          - hel1
          - fsn1
          - nbg1
          - ash
          - hil
        description: Location to deploy the server to

jobs:
  terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Apply
        env: 
          TF_VAR_hostname: ${{ github.event.inputs.hostname }}
          TF_VAR_username: ${{ github.event.inputs.username }}
          TF_VAR_password: ${{ github.event.inputs.password }}
          TF_VAR_ssh_key: ${{ github.event.inputs.ssh_key }}
          TF_VAR_ssh_port: ${{ github.event.inputs.ssh_port }}
          TF_VAR_instance_type: ${{ github.event.inputs.type }}
          TF_VAR_flavor: ${{ github.event.inputs.flavor }}
          TF_VAR_location: ${{ github.event.inputs.location }}
          TF_VAR_hcloud_token: ${{ secrets.TF_VAR_hcloud_token }}
          TF_VAR_tailscale_api_key: ${{ secrets.TF_VAR_tailscale_api_key }}
          TF_VAR_hetzner_dns_token: ${{ secrets.TF_VAR_hetzner_dns_token }}
        run: terraform apply -auto-approve -input=false