name: Create new box

on:
  workflow_dispatch:
    inputs:
      hostname:
        type: string
        default: ""
        description: Hostname of the box
      tenant:
        type: choice
        default: alleaffengaffen
        description: "Tenant to join the server to"
        options:
        - alleaffengaffen
        - root
      password:
        type: string
        default: ""
        description: Password for PAM/code-server
      ssh_port:
        type: string
        default: '22'
        description: SSH port (most times companies block outgoing tcp/22 but may allow tcp/443)
      type:
        type: choice
        default: cax11
        options:
          - cx11
          - cpx11
          - cx21
          - cpx21
          - cx31
          - cpx31
          - cax11
          - cax21
          - cax31
        description: Size of the box to create (cax=arm64)
      image:
        type: choice
        default: ubuntu-22.04
        options:
          - ubuntu-22.04
          - debian-11
        description: OS Image
      location:
        type: choice
        default: hel1
        options:
          - hel1
          - fsn1
          - nbg1
          - ash
          - hil
        description: Location of the box

jobs:
  terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest
    env:
      TF_VAR_hostname: ${{ github.event.inputs.hostname }}
      TF_VAR_username: ${{ github.actor }}
      TF_VAR_password: ${{ github.event.inputs.password }}
      TF_VAR_ssh_port: ${{ github.event.inputs.ssh_port }}
      TF_VAR_type: ${{ github.event.inputs.type }}
      TF_VAR_image: ${{ github.event.inputs.image }}
      TF_VAR_location: ${{ github.event.inputs.location }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Apply (alleaffengaffen.org.github)
        if:  github.event.inputs.tenant == 'alleaffengaffen'
        env: 
          TF_VAR_hcloud_token: ${{ secrets.hcloud_token_alleaffengaffen }}
          TF_VAR_hetzner_dns_token: ${{ secrets.hetzner_dns_token }}
        run: terraform apply -auto-approve -input=false
      - name: Terraform Apply (the-technat.github)
        if: github.event.inputs.tenant == 'root'
        env:
          TF_VAR_hcloud_token: ${{ secrets.hcloud_token_root }}
          TF_VAR_hetzner_dns_token: ${{ secrets.hetzner_dns_token }}
        run: terraform apply -auto-approve -input=false
      - name: Terraform Output
        run: |
          terraform output > $GITHUB_STEP_SUMMARY