name: Create new instance

on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        description: Instance flavor 
        options: 
        - a1-ram2-disk20-perf1
        - a1-ram2-disk50-perf1
        - a2-ram4-disk20-perf1
        - a2-ram4-disk50-perf1
        - a4-ram8-disk20-perf1
        - a4-ram8-disk50-perf1
        - a4-ram16-disk20-perf1
        - a4-ram16-disk50-perf1
      password:
        type: string
        description: Password of user technat
        required: true

jobs:
  terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Apply
        env: 
          TF_VAR_openstack_token: ${{ secrets.TF_VAR_openstack_token }}
          TF_VAR_openstack_user: ${{ secrets.TF_VAR_openstack_user }}
          TF_VAR_tailscale_api_key: ${{ secrets.TF_VAR_tailscale_api_key }}
          TF_VAR_instance_flavor: ${{ github.event.inputs.flavor }}
          TF_VAR_user_password: ${{ github.event.inputs.password }}
        run: terraform apply -auto-approve -input=false
