name: Create new box

on:
  workflow_dispatch:
    inputs:
      hostname:
        type: string
        default: ""
        description: Hostname of the box
      type:
        type: choice
        default: cax11
        options:
          - cx11
          - cpx11
          - cx21
          - cpx21
          - cx31
          - cpx31
          - cax11
          - cax21
          - cax31
        description: Size of the box to create (cax=arm64)
      location:
        type: choice
        default: hel1
        options:
          - hel1
          - fsn1
          - nbg1
          - ash
          - hil
        description: Location of the box

env:
  STATE_BUCKET: "gh-tevbox"
  STATE_BUCKET_REGION: "eu-west-1" 
  TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
  TF_VAR_hetzner_dns_token: ${{ secrets.HETZNER_DNS_TOKEN }}

jobs:
  terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::351425708426:role/gh-tevbox
          role-session-name: tevbox
          aws-region: ${{ env.STATE_BUCKET_REGION }}
      - name: Create Terraform backend configuration
        run: |
          tee s3.tfbackend << END
            bucket = "${{ env.STATE_BUCKET }}"
            key    = "${{ github.event.inputs.hostname }}"
            region = "${{ env.STATE_BUCKET_REGION }}"
          END
      - name: Create variables file
        run: |
          tee ${{ github.event.inputs.hostname }}.tfvars << END
            hostname = "${{ github.event.inputs.hostname }}"
            username = "${{ github.actor }}"
            type     = "${{ github.event.inputs.type }}"
            location = "${{ github.event.inputs.location }}"
          END
      - name: Save variables file to s3
        run: aws s3 cp ${{ github.event.inputs.hostname }}.tfvars s3://${{ env.STATE_BUCKET }}/${{ github.event.inputs.hostname}}.tfvars
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=s3.tfbackend
      - name: Terraform Apply 
        run: terraform apply -auto-approve -input=false -var-file ${{ github.event.inputs.hostname }}.tfvars
      - name: Terraform Output
        run: |
          terraform output > $GITHUB_STEP_SUMMARY
