name: Delete a box

on:
  workflow_dispatch:
    inputs:
      hostname:
        type: string
        default: ""
        description: Hostname of the box

jobs:
  terraform:
    name: "Terraform Run"
    runs-on: ubuntu-latest
    env:
      TF_VAR_hostname: ${{ github.event.inputs.hostname }}
      TF_VAR_hcloud_token: ${{ secrets.hcloud_token_root }}
      TF_VAR_hetzner_dns_token: ${{ secrets.hetzner_dns_token }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Terraform backend configuration
        run: |
          tee s3.tfbackend << END
            bucket = "tevbox-state"
            key    = "${{ github.event.inputs.hostname }}"
            region = "eu-west-1"
          END
      - name: Grab variables file from s3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: mv
          source: s3://tevbox-state/${{ github.event.inputs.hostname}}.tfvars
          destination: ${{ github.event.inputs.hostname }}.tfvars
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=s3.tfbackend
      - name: Terraform Apply 
        run: terraform destroy -auto-approve -input=false -var-file ${{ github.event.inputs.hostname }}.tfvars
