name: Destroy an instance

on:
  workflow_dispatch:
    inputs:
      hostname:
        required: true
        type: string
        description: "Hostname of the instance to delete"

env:
  DOMAIN: "technat.dev"
  TAILNET: "alleaffengaffen.org.github"

jobs:
  destory:
    name: "Destroy run"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Get instance ID
        if: always()
        run: |
          SERVER_ID=$(curl --fail-with-body -sSL -X GET -H "Authorization: Bearer ${{ secrets.TF_VAR_hcloud_token }}" \
            https://api.hetzner.cloud/v1/servers \
            | jq ".servers[] | select(.name==\"${{ github.event.inputs.hostname }}\") | .id" \
            | tr -d "\"")
          echo "SERVER_ID=$SERVER_ID" >> $GITHUB_ENV
      - name: Delete instance
        if: always()
        run: |
          curl --fail-with-body -sSL -X DELETE -H "Authorization: Bearer ${{ secrets.TF_VAR_hcloud_token }}" \
          "https://api.hetzner.cloud/v1/servers/${{ env.SERVER_ID }}"
      - name: Lookup DNS Zone ID
        if: always()
        run: |
          ZONE_ID=$(curl --fail-with-body -sSL -X GET -H "Auth-API-Token: ${{ secrets.TF_VAR_hetzner_dns_token}}" \
            https://dns.hetzner.com/api/v1/zones \
            | jq ".zones[] | select(.name==\"${{ env.DOMAIN}}\") | .id " \
            | tr -d "\"")
          echo "ZONE_ID=$ZONE_ID" >> $GITHUB_ENV
      - name: Lookup DNS Record ID
        if: always()
        run: |
          RECORD_ID=$(curl --fail-with-body -sSL -X GET -H "Auth-API-Token: ${{ secrets.TF_VAR_hetzner_dns_token }}" \
            "https://dns.hetzner.com/api/v1/records?zone_id=${{ env.ZONE_ID }}" \
            | jq ".records[] | select(.name==\"${{ github.event.inputs.hostname }}\") | .id" \
            | tr -d "\"")
          echo "RECORD_ID=$RECORD_ID" >> $GITHUB_ENV
      - name: Delete DNS Record
        if: always()
        run: |
          curl --fail-with-body -sSL -X "DELETE" -H "Auth-API-Token: ${{ secrets.TF_VAR_hetzner_dns_token }}" \
          "https://dns.hetzner.com/api/v1/records/${{ env.RECORD_ID }}"
      - name: Get Tailscale device ID
        if: always()
        run: |
          DEVICE_ID=$(curl --fail-with-body -sSL -X "GET" -u "${{ secrets.TF_VAR_tailscale_api_key}}:" \
            "https://api.tailscale.com/api/v2/tailnet/${{ env.TAILNET}}/devices" \
            | jq ".devices[] | select(.name | test(\"${{ github.event.inputs.hostname }}.+\")) | .id" \
            | tr -d "\"")
          echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_ENV
      - name: Delete Tailscale  device
        if: always()
        run: |
          curl --fail-with-body -sSL -X "DELETE" -u "${{ secrets.TF_VAR_tailscale_api_key }}:" \
          "https://api.tailscale.com/api/v2/device/${{ env.DEVICE_ID }}" 
