name: Hcloud checks

on:
  pull_request:
  push:

jobs:
  terraform:
    name: "Terraform hcloud Checks"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: add terraform backend override
        run: |
          cat <<EOF > backend_override.tf
          terraform {
            backend "local" {
              path = "./.local-state"
            }
          }
          EOF
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false
      - name: terraform init
        id: init
        run: terraform -chdir=hcloud init 
      - name: terraform validate
        id: validate
        run: terraform -chdir=hcloud validate -no-color
