name: Hcloud checks

on:
  pull_request:
  push:

jobs:
  terraform:
    name: "Terraform hcloud Checks"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      STATE_BUCKET: "gh-tevbox"
      STATE_BUCKET_REGION: "eu-west-1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::351425708426:role/gh-tevbox
          role-session-name: tevbox
          aws-region: ${{ env.STATE_BUCKET_REGION }}
      - name: create Terraform backend configuration
        run: |
          tee hcloud/s3.tfbackend << END
            key    = "ci"
            bucket = "${{ env.STATE_BUCKET }}"
            region = "${{ env.STATE_BUCKET_REGION }}"
          END
      - name: Terraform init
        id: init
        run: terraform -chdir=hcloud init -backend-config=s3.tfbackend
      - name: Terraform validate
        id: validate
        run: terraform -chdir=hcloud validate -no-color
