name: Hcloud checks

on:
  pull_request:
  push:

jobs:
  terraform:
    name: "Terraform hcloud Checks"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: add terraform backend override
        run: |
          cat <<EOF > hcloud/backend_override.tf
          terraform {
            backend "local" {
              path = "./.local-state"
            }
            required_providers {
              hcloud = {
                source  = "hetznercloud/hcloud"
                version = "1.49.0"
              }
              hetznerdns = {
                source  = "timohirt/hetznerdns"
                version = "2.2.0"
              }
              tailscale = {
                source  = "tailscale/tailscale"
                version = "0.17.2"
              }
            }
          }
          EOF
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.3
          terraform_wrapper: false
      - name: terraform init
        id: init
        run: terraform -chdir=hcloud init 
      - name: terraform validate
        id: validate
        run: terraform -chdir=hcloud validate -no-color
